version: '3.9'
services:
  flask:
    build: ./flask_code
    ports:
      - "5000:5000"
    volumes:
      - ./flask_code:/src
    depends_on:
      - redis
  redis:
    image: redis
    ports:
      - "6379:6379"
  worker:
    build:
      context: ./flask_code
    entrypoint: rq worker --url=redis://redis:6379
    depends_on:
      - redis
      - flask