- hosts: all

  vars:
    pip_install_packages:
      - name: docker
  tasks:
    - name: Install python3-pip
        shell: |
          sudo apt update
          sudo apt install python3-pip

  roles:
    - geerlingguy.pip
    - geerlingguy.docker