---
- hosts: all
  remote_user: root

- hosts: myserver
  gather_facts: no

  tasks:
    - name: Clone a github repository
      ansible.builtin.git:
        repo: git@github.com:SulavChhetri/rq_redis_flask.git
        dest: /home/rq_redis_flask/

    - name: Run docker-compose up
      become: true
      shell:
        cmd: "docker-compose up -d"
        chdir: /home/rq_redis_flask/
